services:
  frontent:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_SECURITY_USER_NAME=${SECURITY_USER_NAME}
        - VITE_SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "80:80"

  backend:
    build: ./service
    container_name: service
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

  postgres:
    image: postgres:18
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - carrier-hub-data:/var/lib/pg-ddb/data

volumes:
  carrier-hub-data: